# Site settings
title: "Lanchc"
email: lanchc@sohu.com
description: "这是一个简单的博客"
baseurl: ""
url: "https://lanchc.github.io/"
title_description: "懒虫联系邮箱:lanchc@sohu.com"
title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
github_repository: https://github.com/lanchc/lanchc.github.io
post_limit: 5

# Social usernames/URLs
share_github:  lanchc

# Footer
footer_left: "Welcome to <a href=\"https://lanchc.github.io\">Lanchc</a>"
footer_right: "on <a href=\"https://github.com/lanchc\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
